# Generated by Django 6.0.6 on 2026-06-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Contable')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo'), ('PAT', 'Patrimonio'), ('ING', 'Ingreso'), ('EGR', 'Egreso')], max_length=3, verbose_name='Tipo de Cuenta')),
                ('naturaleza', models.CharField(choices=[('DEU', 'Deudora'), ('ACR', 'Acreedora')], max_length=3, verbose_name='Naturaleza')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='contabilidad.cuenta', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
            },
        ),
    ]
