# Generated by Django 6.0.6 on 2026-06-09 17:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Nro. Asiento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción / Glosa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Libro Diario',
                'ordering': ['-fecha', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Haber')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.asientocabecera', verbose_name='Asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asiento',
            },
        ),
    ]
